# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build mpy

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mpy-cross      
    - name: Test with pytest
      run: |
        mpy-cross urle.py -march=armv7m
        
    - name: Print the version of mpy-cross
      id: print_ver
      run: |
        echo "::set-output name=version::`mpy-corss --version`"
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Europe'
        tz2: 'Dublin'
              
    - name: Zip the artifact
      run: |
        zip urle_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip urle.mpy
        
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: urle_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}
        path: urle_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
